#!/bin/bash

USER="root"
SERVER="ec2-174-129-239-85.compute-1.amazonaws.com"
PORT=22
KEY="$HOME/.ssh/lizardbase.pem"

WWW_DIR="/srv/http/lizard_base"

rsync -v -r --delete -e "ssh -p $PORT -i $KEY" www/ $USER@$SERVER:$WWW_DIR/
